# config/application.yml
defaults: &defaults
  cas_server: https://cas.inria.fr/cas
  admin_list:
    - villa

development:
  mailer:
    address: smtp.gmail.com
    port: 587
    domain: aaa.com
    user_name: aa
    password: bb
    authentication: plain
    enable_starttls_auto: true
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults